/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\ring.glb -t -r public -o src/components/RingModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    geometry_0: THREE.Mesh
  }
  materials: Record<string, THREE.Material>
  animations: unknown[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/ring.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geometry_0.geometry} material={nodes.geometry_0.material} />
    </group>
  )
}

useGLTF.preload('/ring.glb')
